### ISSUE TITLE
Profile menu drop down box title not readable

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#10]
The hover box displays ELC's but the text is not clear. 

![image](https://cloud.githubusercontent.com/assets/14996905/16838782/7543a8d8-49cb-11e6-8bae-af895a09b11f.png)

Then on the actual page: 
![profile](https://cloud.githubusercontent.com/assets/14996905/16838844/d3d8946c-49cb-11e6-86a8-b29521846a0d.JPG)
 
White space an issue again.

I don't know what is intended to go at the bottom of the Facebook, google and twitter tags? Perhaps this has just not been developed yet. Suggestion to add Quick view (displaying the map), related profiles and datasets. 

There's a slight over lap of the RSS feed box, it just needs realignment. 

The disclaimer text needs be replaced with the description of the profile page.

**Comment by prustar** [comment]
In ODC the same for profile menu drop box. This screen shot is the drop box of profiles over the topic page. The grey boxes also very bland on top of each other like this. 

![image](https://cloud.githubusercontent.com/assets/14996905/16839982/6cec5de0-49d2-11e6-9925-f37db4154419.png)

**Comment by acorbi** [comment]
Closing, does not apply anymore
