### ISSUE TITLE
Access to Public transport

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#102]
@Huyeng @ChandaraKhun @samean @punwath 

I've just had a look at your new profile page and like it. However you've added 3 different sectors to the same map and they all would have different related content to each of them. Yet when you toggle on and off these related contents do not change. I would also consider moving related news and announcements to the bottom below publications and laws to allow for the map to fit the full width of the screen otherwise it's difficult to view the map with all the elements upon it. 

![image](https://cloud.githubusercontent.com/assets/14996905/21089958/88c8a4e4-c090-11e6-9bbc-d2ef0cf0180d.png)

**Comment by Huyeng** [comment]
@prustar, thanks for your comments on the page, I will bring to them to discuss with the team.

**Comment by prustar** [comment]
@Huyeng - I like the change well done!
