### ISSUE TITLE
Service charges for electricity

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#103]
@punwath @Huyeng - 
A few comments: 

1. Could you please explain what 'electricity intensity ph x A' means in either footnote or hover '?' as I'm not sure that many people would understand what this stands for. 
2. For the English table it might be useful to translate the value into USD rather than Riel as this makes more sense to English users. 
3. The last column for processing data could be separated into two columns with the no. of days and value as a drop-down selection.   
4. Did you try to use the new data viz application to create some visuals which might be more attractive than the tables? 

![image](https://cloud.githubusercontent.com/assets/14996905/21120629/6c802b9a-c11c-11e6-87f0-420a7eebe590.png)

**Comment by Huyeng** [comment]
> For the English table it might be useful to translate the value into USD rather than Riel as this makes more sense to English users.

@prustar- the original price is in Riel and we can't cover it to the USD, as you know the exchange rate always change. Anyways, we thought that the users can convert it themselves if they would like.

**Comment by Huyeng** [comment]
> Did you try to use the new data viz application to create some visuals which might be more attractive than the tables?

For the data viz, we will consider on that.

**Comment by prustar** [comment]
@Huyeng -- thanks for the response -- but you didn't tell me what  'electricity intensity ph x A' mean?

**Comment by Huyeng** [comment]
There is no explanation in the resource, so the title was changed.
