### ISSUE TITLE
White space

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#11]
It might be just me but when the font isn't so bold then the amount of white space there is really stands out. 

![profile2](https://cloud.githubusercontent.com/assets/14996905/16839268/87844306-49ce-11e6-8f6d-bc1b028b5f01.JPG)

**Comment by acorbi** [comment]
@prustar does this still apply?

**Comment by acorbi** [comment]
This does not apply anymore. closing...
