### ISSUE TITLE
Search profile data on typing each charater make the page frozen sometimes

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#129]
It was feed-backed that the ELC profile is stuck when type to find some information using the search box.
https://opendevelopmentcambodia.net/profiles/economic-land-concessions/

**Comment by Huyeng** [comment]
I will change the function from keyup to keypress. The function will start searching when the enter key is press.

**Comment by acorbi** [comment]
ok sounds good
--
Gesendet von der myMail-App für Android Montag, 20 März 2017, 10:16vorm. +01:00 von Huy Eng  notifications@github.com :
