### ISSUE TITLE
Enable auto-search on typing

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#141]
On profile page, currently the users can search by keywords unless pressing the enter key. Without the search button, some of users frequently thought that the function doesn't work because they don't know that they need to press the Enter key. Thus, it was suggested to enable automatically search once typing.  

From last user experiences, automatically search on key up was disabled because it caused the page freezing if the page contains many data like ELCs profile. 

To figure out this, I will re-enable the auto-search function for the keywords search, but the function will work after finishing the typing. 

![fcd1ede957c23563617c6e02cb186b384038b166139fc316bd pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/6613530/25262233/cfff24a4-2680-11e7-81ee-6a78833c5bdf.jpg)

**Comment by acorbi** [comment]
@huyeng I would rather think of adding a [Filter] button on the filter bar to keep consistency with other elements of the site auch as archive or search pages.

**Comment by Huyeng** [comment]
There is no much space on this filter bar as it also has the related profiles there.  
Moreover, the filter lists also automatically filter once selected.  
If we would like to keep things consistency, so we we should update the other filters to make them automatically search.  I think, the automatic function is thing that most users prefer to especially on the table. 
It was aware that updating the archive and search page to be automatically search may have some challenges since there are many different contents. That's why the team didn't suggest about this.

**Comment by acorbi** [comment]
> I think, the automatic function is thing that most users prefer to especially on the table.

I agree that it is more user-friendly than clicking the button. 

Please go ahead and implement the change you are suggesting
