### ISSUE TITLE
Budget and procurement

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#147]
@samean @punwath @ChandaraKhun 
I don't know which one of you created this visual but I wanted to know what the .x2 means here? 

![image](https://cloud.githubusercontent.com/assets/14996905/25380218/c23c715a-29af-11e7-9a5f-90d5580e429e.png)

Thanks, P

**Comment by acorbi** [comment]
@prustar can you add a link to the related page?

**Comment by Huyeng** [comment]
Fixed.
