### ISSUE TITLE
Profile Page: Enable thematic maps 

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#15]
The current profile page for hydropower would be better served if the user could enable the display of the entire set (dams, reservoirs, transmission lines, sub-stations) upon the profile as they do in the map explorer.

Is this possible in the current template? Otherwise it's a very disjointed dataset.

**Comment by acorbi** [comment]
@prustar currently it is possible to embed a thematic map on the body of the profile page. However it would not be filtered if the user inputs something on the search field on the table. Let's leave this feature request open and put it on the pipeline according to its priority

**Comment by acorbi** [comment]
@prustar the functionalities described on this Issue should be now implemented, can you please check and if working, close the issue?

**Comment by Huyeng** [comment]
I think the issue should be closed, and we can create new issue if needs.
