### ISSUE TITLE
Create a new template that will have a sub-navigation (menu area)

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#150]
Needs a new template to present the new election project and the migrated election from the old site.
The template of election is requested to have the sub navigation as the old site. 
![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/26566821/4f022d10-4520-11e7-9478-13790b33457e.jpg)

**Comment by acorbi** [comment]
Adding more details to your github issue:
- The subnavigation will be implemented with as a menu area that can be populated with a **Custom menu** http://www.wpbeginner.com/beginners-guide/how-to-add-navigation-menu-in-wordpress-beginners-guide/
- The new template will be used to implement the different sections reflected above.
