### ISSUE TITLE
Add social buttons on profiles

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#155]
Currently, profile pages such as https://opendevelopmentcambodia.net/profiles/community-forestry/ do not expose the social buttons which allow users to share the content on social media easily.

![screenshot from 2017-06-05 11-50-27](https://cloud.githubusercontent.com/assets/384894/26779342/46cfb0e4-49e5-11e7-8289-fe5c97f5611e.png)

**Comment by acorbi** [comment]
Currently, the **Download and metadata** button on profiles is right where the social buttons are presented on other sites such as the single news or topics page: https://pp.opendevelopmentcambodia.net/announcements/ministry-of-environment-offically-lunched-the-lexicon-of-climate-change-in-khmer/

![screenshot from 2017-06-13 14-26-46](https://user-images.githubusercontent.com/384894/27082276-70745098-5044-11e7-83db-125bbd35cf69.png)

@DragonVirus @Huyeng @gimmemochi Where would you add the social buttons? You have any idea?

**Comment by DragonVirus** [comment]
Just top of the sidebar (Just above the download metadata section) ? 

And in new data detail page mockup i'm planning to move the download metadata section to just beside **Additional Info** title. I think having that at sidebar is a bit confusing to the users. Well ..  at least for me. :joy: 

<img width="896" alt="screen shot 2017-06-14 at 1 49 17 pm" src="https://user-images.githubusercontent.com/1311765/27120164-8af10884-5108-11e7-8339-f2f78cc011d2.png">

**Comment by Huyeng** [comment]
I would like to suggest to add the social media icons like this:
![screenshot_1](https://user-images.githubusercontent.com/6613530/29268911-2cec3ba0-8119-11e7-9637-76a6157d043d.jpg)

Shows the words "Download and View Metadata" on mouse hover.
