### ISSUE TITLE
The hierarchy of map layer category doesn't work on map of profile page

### ISSUE THREAD

**Issue by punwath** [OpenDevelopmentMekong/wp-odm_profile_pages#156]
I just added several layers with category and sub-category to the profile page but it doesn't show up with hierarchy. For example, it happens in this profile page: https://opendevelopmentcambodia.net/?post_type=profiles&p=105176&preview=true
![image](https://cloud.githubusercontent.com/assets/18112596/26821271/16150f9e-4ad0-11e7-86e4-21c2be919e7e.png)

**Comment by acorbi** [comment]
@Huyeng can you please take a look at this?

**Comment by Huyeng** [comment]
I will take a look at soon.

**Comment by acorbi** [comment]
thanks

**Comment by Huyeng** [comment]
It was recalled that, the first idea to present the interactive map on the profile page, it doesn't present the layers in hierarchy level, just grouped by its category. 

In case for the election map, I think the hierarchy is requested. Then I will enhance the code to provide he option to demonstrate the layer in hierarchy as the interactive map.

**Comment by acorbi** [comment]
@Huyeng @punwath Now that https://github.com/OpenDevelopmentMekong/wp-odm_theme/issues/992 has been implemented. can we then close this issue? If so, please do.

**Comment by Huyeng** [comment]
Fixed now. 

![screenshot_9](https://user-images.githubusercontent.com/6613530/27113906-1af1aac0-50ea-11e7-94f9-3b90f5bd77b6.jpg)
