### ISSUE TITLE
Can't view all table of profile on mobile (not responsive on mobile)

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#159]
<img width="569" alt="screenshot at jun 16 13-46-09" src="https://user-images.githubusercontent.com/6613530/27215036-b594ece4-5299-11e7-8e4f-bd81df7ce19c.png">

Fixes header of table has blocked the table.

**Comment by Huyeng** [comment]
<img width="569" alt="screenshot at jun 16 13-46-09" src="https://user-images.githubusercontent.com/6613530/27215036-b594ece4-5299-11e7-8e4f-bd81df7ce19c.png">

Fixes header of table has blocked the table.

**Comment by acorbi** [comment]
duplicated (it is already being logged on https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/issues/160 ), closing.
