### ISSUE TITLE
The download icon on Profile page is so messy

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_profile_pages#16]
![854beb0a-5d94-11e6-9d48-f87596adaf30](https://cloud.githubusercontent.com/assets/18528756/17615557/44c37636-6099-11e6-9ce8-5b612bcee583.png)

**Comment by S-mardii** [comment]
Metadata button actually link to a page that users can download the files. Then how about a single button for both viewing metadata and download.

**Comment by Huyeng** [comment]
The design was changed.  The buttons are not existing any more.
