### ISSUE TITLE
Responsive: Filter box fixed on top of table on profile pages takes too much space

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#160]
## Issue description

Currently, the tables of profile pages (Example: https://opendevelopmentcambodia.net/profiles/economic-land-concessions/ ELC pages) are not responsive. Specifically, the filtering box, which is fixed on the top when users scroll down, takes too much vertical space which makes navigation of contents too unusable.
![screenshot from 2017-07-17 14-50-16](https://user-images.githubusercontent.com/384894/28268623-44157ed4-6aff-11e7-9af3-d2f95b55d9ff.png)

## Proposed solution

The solution consists on making the filters accessible via a button on small devices. The expected changes to be applied and the behaviiour of the UI would be:

- [ ] Adapt layout of filter box on small devices (only) so they are accessible via a sliding panel (from the sidebar) instead of being shown all the time.

![screenshot from 2017-07-17 14-52-48](https://user-images.githubusercontent.com/384894/28268728-9d86989a-6aff-11e7-9383-2f1fe3d1a994.png)

Note as well that the search input field ( Search data...) is rendered differently and it continues to be accessible directly without needing to click any button. This search field, together with the filter button, should be made fixed on the top of the page (directly underneath the main top bar with country/language selector) when user scrolls down

- When the user clicks on the filter button, the sidebar with the filtering options will slide-in from the side.

![screenshot from 2017-07-17 14-56-00](https://user-images.githubusercontent.com/384894/28268844-18b4f0fc-6b00-11e7-9739-2909f6190e14.png)

- [ ] Once this is presented, the user will be able to select a series of values for the filters which will then be applied once the user clicks the [Search] button. The user can also click on the [x] on the top-right corner to close the dialog and go back to the profile page

- [ ] Study changing the wording of the button from [Search] to [Filter]

- [x] The datatables responsive extension https://datatables.net/extensions/responsive/ should be installed and configured

- [ ] In case the number of columns shown is too large, we should think about implementing a view more button to expand the list or take the user to the profile detail page.

**Comment by acorbi** [comment]
An idea would be to hide the filter box per default and add a FILTER icon (http://fontawesome.io/icon/filter/) with the text FILTER that the user can click . this filter icon will be placed on the right side of the **textual search** field, which will be presented all the time on all the filters:

`
[           Enter search term......     ]  [  FILTER ]
----------
Table
________
`

Once the filter buton is clicked, a sidebar menu with the filtering possibilities will slide-in from right to left, similar to:

![screenshot from 2017-07-06 11-36-29](https://user-images.githubusercontent.com/384894/27905376-03a5e1c6-6240-11e7-8f71-d042ce0ef4a5.png)

**Comment by DragonVirus** [comment]
@Huyeng 
For responsive table, we could use this datatable extension https://datatables.net/extensions/responsive/

**Comment by acorbi** [comment]
@DragonVirus @Huyeng Let's test the extension again and try to make it work.

**Comment by acorbi** [comment]
@DragonVirus One idea I just had in regards to exposing the filters on a sliding sidebar menu. I think it would be better to present the filters on a sort of pop-up window which would work and look the same way the layer selection box would work for the map explorer. Something similar to the image below:

![Uploading Screenshot from 2017-07-12 16-32-46.png…]()

**Comment by acorbi** [comment]
@Huyeng @DragonVirus I am updating the description of this issue to reflect the proposed solution based on the mockups done by @DragonVirus
