### ISSUE TITLE
Profile Page: Looking for a better template for the filter box

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_profile_pages#18]
![screenshot 1](https://cloud.githubusercontent.com/assets/18528756/17616101/bace172a-609c-11e6-86ed-ef208338496e.png)

**Comment by S-mardii** [comment]
Suggested sample:
![image](https://cloud.githubusercontent.com/assets/18528756/17616113/ceca6436-609c-11e6-88b5-b21fc27cdd71.png)

**Comment by acorbi** [comment]
@S-mardii I understand you would center the filter possibilities so they are better aligned. I like the idea.

**Comment by acorbi** [comment]
@Huyeng this has been fixed with https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/pull/107, correct? can we close this issue?

**Comment by Huyeng** [comment]
Yes.
