### ISSUE TITLE
CSV table not showing up on Profile

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#183]
Testing a new profile: https://pp.opendevelopmentmekong.net/profiles/early-warning-system/

![image](https://user-images.githubusercontent.com/14996905/36881651-995b2fd6-1dfd-11e8-8ccc-e357bc297847.png)

The table doesn't appear. I tested adding two links: 
https://data.pp.opendevelopmentmekong.net/dataset/early-warning-system and the resource: 
https://data.pp.opendevelopmentmekong.net/dataset/early-warning-system/resource/b85ac31c-5a41-4df8-bc11-382f9f361d74?type=dataset

neither worked, and when you select on the map it also doesn't lead to the table or resource page in WP.

**Comment by prustar** [comment]
So when I select the download on the map it takes me to dataset not found page: 

![image](https://user-images.githubusercontent.com/14996905/36881788-72c999f6-1dfe-11e8-8a7d-b18b56b9b51f.png)

When I select i for more info on the legend it provides no information about the dataset whatsoever. 
![image](https://user-images.githubusercontent.com/14996905/36881807-936d4676-1dfe-11e8-95ca-f9a41e8ac53a.png)

It should display the metadata from the CKAN resource.

**Comment by prustar** [comment]
@acorbi Thanks for making this visible now... 

Another issue. The profile page has a function to direct users to an external url like we did for the Chinese financial aid profile - but for some reason in PP although the hyperlink seems to be enabled the link spits out an error. Note on the screenshot below when I hover on the hyperlink: 

![image](https://user-images.githubusercontent.com/14996905/36946022-dfb8ab6e-1fe4-11e8-9b37-9b4d8a63675c.png)

On Production I've made the profile live however the column that should be hyperlinked isn't at all?  https://opendevelopmentmekong.net/profiles/early-warning-system/?preview_id=9141106&preview_nonce=40b0f2165f&_thumbnail_id=-1&preview=true

![image](https://user-images.githubusercontent.com/14996905/36946029-fec2b374-1fe4-11e8-9ee5-03215022f8e6.png)

**Comment by acorbi** [comment]
@prustar now it is fixed, the value entered on the field **Column ids linking to detail page (English)** had a whitespace at the end which needed to be removed in order to make it work.

One suggestion: Optimally, you would add **featured images** to the profiles so they are a bit more appealing on the profile list page: https://opendevelopmentmekong.net/profiles/

![screenshot from 2018-03-04 17-19-27](https://user-images.githubusercontent.com/384894/36947742-526c5652-1fd0-11e8-9e6a-7de7d537079a.png)

**Comment by prustar** [comment]
@acorbi Thanks! Also for reminder of image...
