### ISSUE TITLE
Profile pages show the referent document incorrectly when click on map feature

### ISSUE THREAD

**Issue by vatana92** [OpenDevelopmentMekong/wp-odm_profile_pages#202]
There is another issue related to presenting the incorrect reference documents on the profile page when you click the on the feature on map to view detail. Please go to this link and you will see the attached image: https://opendevelopmentcambodia.net/profiles/allocated-land-for-social-land-concession/

For the example: "Peam SLC"
![image](https://user-images.githubusercontent.com/19201022/44319468-3bb2e780-a466-11e8-81ef-62d197c59739.png)

How it looks on the detail page of that feature: https://opendevelopmentcambodia.net/profiles/allocated-land-for-social-land-concession/?feature_id=1
There are dozens of the reference document, while the in the dataset there is only two. 

![image](https://user-images.githubusercontent.com/19201022/44319737-eaa3f300-a467-11e8-8b10-44eec13627f0.png)

But we you go to see the dataset on CKAN, there are only 2 references: "World_bank_LASEDII__25.04.2016.pdf;Sub_decree_No_255__03.11.2011.pdf"

Link to dataset: https://data.opendevelopmentmekong.net/dataset/allocated-land-for-social-land-concession?type=dataset

Reference of  "Peam SLC" on the CSV file downloaded from the dataset.
![image](https://user-images.githubusercontent.com/19201022/44319665-7cf7c700-a467-11e8-97de-470e5926efd2.png)

**Comment by Huyeng** [comment]
After checking, it could define the error that there is no referenced file available on the CKAN, then some of related dataset was queried instead which caused of showing a number of referent docs on the page. 

Please ensure that all the reference files are uploaded. I will update the script to prevent this happen soon

**Comment by vatana92** [comment]
The resources have been already existed.
For "Sub_decree_No_255__03.11.2011.pdf"
https://data.opendevelopmentmekong.net/en/laws_record/255-4815-67-1353-735-854-30-975-60-468-78-428-99
For "World_bank_LASEDII__25.04.2016.pdf"
https://data.opendevelopmentmekong.net/library_record/ii

**Comment by Huyeng** [comment]
Fixed
