### ISSUE TITLE
Unwanted blank space between the fixed filter panel and Table on Scroll

### ISSUE THREAD

**Issue by S-mardii** [OpenDevelopmentMekong/wp-odm_profile_pages#225]
When scrolling on some profile page, there is a huge white space between fixed filter panel and table.

Link: https://opendevelopmentcambodia.net/km/profiles/foreign-investment-in-cambodia

![image](https://user-images.githubusercontent.com/18528756/155461615-9d9e736f-f592-4a35-b50b-b19b27c0dabc.png)

**Comment by arky** [comment]
@S-mardii Fixed by removing or overriding CSS rule  "margin-top: 191px;"

**Comment by arky** [comment]
@S-mardii My best guess reading the code here is that this might be the source of that CSS rule. 

https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/blob/d7976f605ec468afd96dee7deed2f826a4dbea2e/post-types/templates/page-profiles-list-page.php#L99
