### ISSUE TITLE
Profile page // Oil & Gas ODMyanmar

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#31]
This warning appears: 
![image](https://cloud.githubusercontent.com/assets/14996905/18124859/552da854-6f74-11e6-9d50-d87e045b6ffb.png)

Inconsistencies on the logo for file types: 

![image](https://cloud.githubusercontent.com/assets/14996905/18124878/6eb7dbaa-6f74-11e6-8a6f-2d6a5cba133b.png)

**Comment by acorbi** [comment]
Fixed via https://myanmar.opendevelopmentmekong.net/profiles/oil-and-gas-blocks/
