### ISSUE TITLE
Profile page // Oil & Gas ODMyanmar - edit map view please

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#32]
@yanoak @DragonVirus @thetaung2 

Please edit the map to filter by another category if there is one to choose, perhaps size or another distinguishing factor and change the colours. Format the info windows according to the standard styling - see example below. 

[profile info window example.txt](https://github.com/OpenDevelopmentMekong/wp-odm_profile_pages/files/446938/profile.info.window.example.txt)

**Comment by yanoak** [comment]
Fixed.

**Comment by acorbi** [comment]
@yanoak @prustar can we close this then?

**Comment by acorbi** [comment]
@yanoak @prustar can we close this then?

**Comment by yanoak** [comment]
@acorbi yup we can close this
