### ISSUE TITLE
Download resources buttons missing on profile pages

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#33]
On profile pages (example https://cambodia.opendevelopmentmekong.net/profiles/economic-land-concessions/ or https://cambodia.opendevelopmentmekong.net/profiles/fisheries-conservation-areas/), download buttons for the different resources are missing. This issue appeared after 4a824d13317596fd5699489199a76d0e7a44f5f9

![screenshot from 2016-08-31 12-34-51](https://cloud.githubusercontent.com/assets/384894/18125663/b8b8a7e0-6f77-11e6-87ea-4762788f4ca5.png)

Expected behaviour is to have a series of buttons to allow users to download the existing resources related to the profile page

**Comment by Huyeng** [comment]
I would like to point to the data page that contains both meta and download:
https://cambodia.opendevelopmentmekong.net/km/dataset/?id=map_fish_consumption
What do you think?

**Comment by acorbi** [comment]
Sounds good! That would make it more streamlined

**Comment by Huyeng** [comment]
Any suggestion to name the button?

**Comment by Huyeng** [comment]
Close it now.
