### ISSUE TITLE
Profile page stats needs formatting

### ISSUE THREAD

**Issue by prustar** [OpenDevelopmentMekong/wp-odm_profile_pages#34]
See below: 
![image](https://cloud.githubusercontent.com/assets/14996905/18126128/f914d6d6-6f79-11e6-8990-e3be46252139.png)

Perhaps a simply visual for the stats might be better than to list it and have it placed on the map somewhere as there's space. 

Formatting of the search is also a bit off and just needs to be realigned and as you scroll the table heading doesn't move up: 

![image](https://cloud.githubusercontent.com/assets/14996905/18126203/5ea19566-6f7a-11e6-9518-ef4137976396.png)

**Comment by Huyeng** [comment]
It should be fixed after merging the code in PR: https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/pull/11
