### ISSUE TITLE
Keep textdomain domain name syntax consistant with other plugins

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#48]
on https://github.com/OpenDevelopmentMekong/wp-odm_tabular_pages/blob/master/wp-odm_tabular_pages.php#L61 textdomain domain name is same as the name of the plugin.

in order to keep this consistant, it should be the same in case of wp-odm_profile_pages

**Comment by Huyeng** [comment]
I don't mind with that if you would like to use the same name as the plugin name. I prefer the short name, 
Anyways, while you are working not please update the texts domain of some strings that have not updated after merging. Actually, those already updated, but after merging, some of them have not updated.  see the screenshots below: 
For example, the text domain of Textual search was updated to odm_profile in impl-44,
<p><?php _e('Textual search', 'odm_profile');?></p>, but after merging, the texts domain is still odm. 

![screenshot_17](https://cloud.githubusercontent.com/assets/6613530/19508037/111b47e4-9601-11e6-97e6-1852238d6629.jpg)

After merging:
![screenshot_18](https://cloud.githubusercontent.com/assets/6613530/19508075/48fee1ac-9601-11e6-9aa8-a77ad745c557.jpg)
