### ISSUE TITLE
Errors on profile with multi-layered maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#54]
If a map with different views is linked to a profile, some errors occur while trying to filter the information using the search field

![screenshot from 2016-10-20 12-34-38](https://cloud.githubusercontent.com/assets/384894/19568991/e00e1200-96c1-11e6-9550-d379be3ca5ba.png)

**Comment by Huyeng** [comment]
@acorbi - could you send the link please.

**Comment by Huyeng** [comment]
Please ensure that the spreadsheet contains the map_id field. The map_id is defined as the key to filter the map.

**Comment by Huyeng** [comment]
The is error is no long exist since the new mapping function is deployed. Close it now.
