### ISSUE TITLE
Add the embedded_map function to the all the templates of profile

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#61]
If the layers are selected, the map should be presented for each template of profile include the one with widget.

**Comment by acorbi** [comment]
@Huyeng if I understand correctly, the map is not being presented on the profile template with widget?

**Comment by Huyeng** [comment]
Yes, it is implemented now.

**Comment by acorbi** [comment]
Closing
