### ISSUE TITLE
Separate the Full width middle content in other metabox

### ISSUE THREAD

**Issue by Huyeng** [OpenDevelopmentMekong/wp-odm_profile_pages#63]
Before the full width middle content that list the relevant sub page of the access to public service of profile were showed, but now it has gone.  

The full width middle content is used to present some information under the map, it is not related to the CKAN dataset setting, so it should split to differently.

**Comment by acorbi** [comment]
@Huyeng was the content added on the profile's body on https://opendevelopmentcambodia.net/wp-admin/post.php?post=98101&action=edit ?

**Comment by Huyeng** [comment]
Was it taken away?

**Comment by acorbi** [comment]
I do not know, but it is not on the post's content. Should it be there?

> it seems the main is not working

What do you mean with **the main** ?

**Comment by Huyeng** [comment]
Nope, it is not. The post content is shown in twelve under the map or at the map container if no map.
The full width content  in the middle, it is the sth that we would like to show under the map or post content across in sixteen column. 

Well, the main site here, I refer to the PROD site. I thought that you are fixing sth on server, it may the reason that I can't open any page of ODC both back-end and front-end. Can you open the ODC site as normal?

**Comment by acorbi** [comment]
> The full width content in the middle, it is the sth that we would like to show under the map or post content across in sixteen column. 

So that **full width content in the middle** is hard-coded on the template? 

> Well, the main site here, I refer to the PROD site. I thought that you are fixing sth on server, it may the reason that I can't open any page of ODC both back-end and front-end. Can you open the ODC site as normal?

Both frontend and dashboard are working correctly for me.. you might have some issues on your side

**Comment by Huyeng** [comment]
> So that full width content in the middle is hard-coded on the template? 
Nope. It is a text box in the CKAN Dataset Resource currently that allow to add the html code to present on the profile page. Now, i would like to separate like this:
![screenshot_8](https://cloud.githubusercontent.com/assets/6613530/19939058/f28c2c44-a159-11e6-8637-17dc42ff8493.jpg)

**Comment by acorbi** [comment]
>  It is a text box in the CKAN Dataset Resource currently that allow to add the html code to present on the profile page

Why CKAN Dataset Resource?

> Now, i would like to separate like this:

yeah, much elegant solution.. but why don't paste the HTML directly on the profile's content? That way you do not need to create that **full-width middle content**. Does it need to be full-width necessarily?

**Comment by Huyeng** [comment]
Yes, it should be there, that's why i would like separate the metabox.

>why don't paste the HTML directly on the profile's content? That way you do not need to create that full-width middle content.

Well, first of all, I would like use the post content to replace the created full-width content too. However,  when there was a question to ask me about presenting sth such as the slide show or data visualization or other feature besides the map, this led me thought that the post's content will be used for that purpose. if the content of the post is used to show sth under the map, what's happen if there is not map, then the area of map will be blank. 

>  Does it need to be full-width necessarily?
Yes, it does. As seen, the proposed template of public service and prey land, both have the list of the sub page under the map.

**Comment by acorbi** [comment]
>  if the content of the post is used to show sth under the map, what's happen if there is not map, then the area of map will be blank. 

if there is no map associated to the profile, I would just do not show it... the post's content would be at the beginning of the post, instead of below the map.

Anyway, I believe that the solution you propose is good.

**Comment by Huyeng** [comment]
>if there is no map associated to the profile, I would just do not show it.
 
Yes, of course. it won't be shown.   

>the post's content would be at the beginning of the post, instead of below the map.

It can change as needs. Currently, they would like to show it under the map, and keep the map be consistent as other pages.

Anyway, it is great that you agreed with creating a full-width content.  Actually, it have already discussed before, but I added the box in wrong place.
