### ISSUE TITLE
Some gas blocks not showing maps on detail page

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#65]
On pages such as https://opendevelopmentmyanmar.net/profiles/oil-and-gas-blocks/?map_id=32, the embedded map is not showing up and some warning messages appear instead. Other blocks such as https://opendevelopmentmyanmar.net/profiles/oil-and-gas-blocks/?map_id=1 work just fine.
![screenshot from 2016-11-06 11-31-13](https://cloud.githubusercontent.com/assets/384894/20036858/9171c988-a414-11e6-9613-e64967c1dcd8.png)

@DragonVirus @yanoak A possible reason could be an inconsistency between the CSV resource on CKAN and the data on the cartodb map (columnd map_id). Have you checked that they are all consistent? I do not have access to odmm carto account

**Comment by yanoak** [comment]
everything seems to be working fine now

**Comment by Huyeng** [comment]
I will check and fix it. 
This is calling the function of embedded map, it should be fix in theme.  
The issue will be closed and moved to wp-odm_theme.

**Comment by Huyeng** [comment]
There is a conflict of "map_id" between the profile and map post type.  
I would like to change the map_id attribute  of the link below to the feature_id/f_id. This does not mean that we need to update the field name in CSV, it just the only the variable of the link below: 
http://myanmar.odm.web/profiles/oil-and-gas-blocks/?map_id=2
==>
http://myanmar.odm.web/profiles/oil-and-gas-blocks/?feature_id=2
