### ISSUE TITLE
Carto map not being updated when filter is entered

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#77]
On profile pages such as https://opendevelopmentcambodia.net/profiles/hydropower-dams/ or http://opendevelopmentmyanmar.net/profiles/oil-and-gas-blocks/ the map is not being updated when the user specifies a filter.

**Steps to reproduce the issue**

1. Go to one of the profiles
2. Enter a text query on the search field
3. The table is then updated but not the map. Expected behaviour is that the map also shows a subset of results which correspond to those listed on the table

**Comment by Huyeng** [comment]
This functions were working properly before. It seems like the updating of JS has broken It.
