### ISSUE TITLE
Notice: Undefined index on Khmer version of profile

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_profile_pages#78]
on https://pp.opendevelopmentcambodia.net/km/profiles/economic-land-concessions/, below the map, the following notice message is presented:

```
Notice: Undefined index: ទិន្នន័យបន្ទាប់បន្សំ in /var/www/html/wp-content/plugins/wp-odm_profile_pages/post-types/templates/page-profiles-list-page.php on line 58
```

![screenshot from 2016-11-15 15-01-05](https://cloud.githubusercontent.com/assets/384894/20308508/839f4f38-ab44-11e6-8292-2d0966591714.png)

Logic of the plugin should be able to handle this situation without throwing a warning

**Comment by Huyeng** [comment]
The issue is not related to the code, but the attribute entered.  It may not update on the PP, but the PROD did.
