### ISSUE TITLE
Nothing in metadata link for Total Eco Land Concession

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/wp-odm_profile_pages#9]
Doesn't indicate anything -- just links to page with no data on it

![metadata-nada](https://cloud.githubusercontent.com/assets/16559612/16830964/2e34dcba-4970-11e6-896d-67f8c015f441.JPG)

![meta-nada2](https://cloud.githubusercontent.com/assets/16559612/16830992/5b4f0464-4970-11e6-8bd3-e664fb691a1b.JPG)

**Comment by prustar** [comment]
The pdf link is also incorrect. It takes you to a report on Urban Transport Institutions and Governance and Integrated Land Use and Transport?
